name: platform

include:
  - docker/service/flatnotes.yml

services:
  platform:
    image: titpetric/platform
    networks:
      - elastic
      - db_storage
    ports:
      - 8080:8080
    env_file: .env.docker

networks:
  db_storage:
    external: true
  elastic:
    driver: bridge
