---
version: "3"

# Setup GOTOOLCHAIN workaround for #75031:
# https://github.com/golang/go/issues/75031#issuecomment-3195256688

vars:
  goversion:
    sh: go env GOVERSION
  toolchain: '{{.goversion}}+auto'

tasks:
  default:
    desc: "Run platform base"
    env:
      PLATFORM_DB_DEFAULT: "mysql://platform:platform@tcp(127.0.0.1:3306)/platform"
      PLATFORM_ENABLE_EXPVAR: "true"
    cmds:
      - goimports -w -local github.com/titpetric/platform .
      - gofumpt -w .
      - CGO_ENABLED=0 go run ./cmd/platform/main.go

  docker:
    desc: "Build docker image"
    cmds:
      - defer: rm platform -f
      - CGO_ENABLED=0 go build ./cmd/platform
      - docker build --no-cache -t titpetric/platform -f docker/Dockerfile .

  clean:
    desc: "Clean build assets"
    cmds:
      - go clean -testcache
      - rm -f ./platform pkg.cov go-fsck.json
      - docker rmi -f titpetric/platform

  migrate:
    desc: "Run migrations"
    cmds:
      - mig lint --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform" --schema platform
      - mig docs --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform" --schema platform --output=./module/user/docs
      - mig gen --db-dsn="platform:platform@tcp(127.0.0.1:3306)/platform" --go.skip-json --schema platform --output=./module/user/model

  bench:
    desc: "Run benchmarks"
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmd: go test -bench=. -benchmem -cpu 1,2,4 -race -v ./...

  test:
    desc: "Run tests with escape analysis"
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
      CGO_ENABLED: 0
      PLATFORM_ENABLE_EXPVAR: "true"
      PLATFORM_ENABLE_OTEL: "true"
#    cmd: coverpkg=$(go list ./... | paste -sd "," -) go test -trimpath -count=1 -gcflags="-l" -cover -coverpkg="$coverpkg" -coverprofile=pkg.cov ./...
    cmds:
      - go test -trimpath -count=1 -cover -covermode=atomic -coverpkg="all" -coverprofile=pkg-original.cov ./...
      - egrep "(^mode:|^$(go list .))" pkg-original.cov > pkg.cov
#    cmd: go test -trimpath -count=1 -gcflags="-l" -cover -coverpkg="github.com/titpetric/platform/...,./..." -coverprofile=pkg.cov ./...

  cover:
    desc: "Show source coverage"
    cmds:
      - defer: rm -f pkg.cov.json
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck extract ./...
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage

  uncover:
    desc: "Show uncovered source"
    cmd: uncover pkg.cov

  setup:
    desc: "Install dev tooling"
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
      - go install mvdan.cc/gofumpt@latest

  up:
    desc: "Bring up docker env"
    cmd: docker compose up -d --remove-orphans

  down:
    desc: "Bring down docker env"
    cmd: docker compose down
